### ISSUE TITLE
Can it works over an existing pod?

### ISSUE THREAD

**Issue by bhack** [ernoaapa/kubectl-warp#10]
It would be useful if this tool could work over an already deployed pod.

**Comment by ernoaapa** [comment]
Interesting. Can you clarify, you would like to (re-)connect to Pod what you have deployed with warp or some other Pod what you have started without warp?

Warp base on sidecontainer with sshd and temporary keys. The former is doable but latter would require that your Pod include this sidecar or you have shared volume with your pod and another sshd pod.

Interested to hear your usecase.

**Comment by bhack** [comment]
Yes the case is to use warp with an already deployed pod (with your own yaml, CD pipeline deployment, helm etc..).
Cause we could have complex pod with volumes etc, or you don't have directly the control of pod deployment so it is hard to work  with these pod with current warp cli interface.

I think we need something like sidecar injector: https://github.com/tumblr/k8s-sidecar-injector/

**Comment by groundnuty** [comment]
@ernoaapa this feature was never implemented as I understand?

**Comment by digitalkram** [comment]
basically a duplicate of #17

**Comment by digitalkram** [comment]
Came here looking for just that while on the hunt for a way to pre-seed a PV (incrementally), it is a pitty this was abandoned 6 years ago.
