### ISSUE TITLE
Can it smart sync with inotify?

### ISSUE THREAD

**Issue by bhack** [ernoaapa/kubectl-warp#11]
https://bartsimons.me/sync-folders-and-files-on-linux-with-rsync-and-inotify/

**Comment by bhack** [comment]
For Go see https://github.com/fsnotify/fsnotify

**Comment by ernoaapa** [comment]
Yeah it would be nice, current 1s loop is quite hacky way, but at least the fsnotify do not support recursive watch :/

**Comment by bhack** [comment]
Probably it is quite easy to have recursion watching https://github.com/fsnotify/fsnotify/issues/41#issue-42591581

**Comment by bhack** [comment]
Watching nested files and directories code snippet:
https://medium.com/@skdomino/watch-this-file-watching-in-go-5b5a247cf71f
