### ISSUE TITLE
Unable to create a pod on a GKE Cluster

### ISSUE THREAD

**Issue by blakestoddard** [ernoaapa/kubectl-warp#2]
Hello hello!

I'm unable to use `kubectl warp` to create a pod on a GKE cluster, here's the error I get:

```
$ kubectl warp -i -t --image ubuntu demo -- /bin/bash
Create the Pod
No Auth Provider found for name "gcp"
```

Anything I can do to help here? (I installed via `brew`)

**Comment by cokeeffe** [comment]
Appears to be caused from lack of GCP client support

`diff --git a/main.go b/main.go
index adfa801..8221214 100644
--- a/main.go
+++ b/main.go
@@ -18,6 +18,7 @@ import (
 	"time"

 	"github.com/ernoaapa/kubectl-warp/cmd"
+	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
 	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
 )
`

**Comment by ernoaapa** [comment]
@cokeeffe Thanks for testing with GKE! Can you provide a pull request? I happily approve that.

**Comment by ernoaapa** [comment]
Fixed by https://github.com/ernoaapa/kubectl-warp/pull/3
