### ISSUE TITLE
Add to Krew package manager

### ISSUE THREAD

**Issue by jmreicha** [ernoaapa/kubectl-warp#4]
It would be nice if this was available as a package in the [Krew](https://github.com/GoogleContainerTools/krew/blob/master/docs/DEVELOPER_GUIDE.md#packaging-plugins-for-krew) package manager.

**Comment by ernoaapa** [comment]
Great idea, thanks @jmreicha!

**Comment by ernoaapa** [comment]
Fixed by https://github.com/GoogleContainerTools/krew-index/pull/54
