### ISSUE TITLE
Doesn't work on GKE clusters: auth plugin missing

### ISSUE THREAD

**Issue by ahmetb** [ernoaapa/kubectl-warp#5]
I get error `No Auth Provider found for name "gcp"`

This is because you need to import gcp kubernetes client auth lib like:

https://github.com/kubernetes/client-go/blob/6134db91200ea474868bc6775e62cc294a74c6c6/examples/out-of-cluster-client-configuration/main.go#L31-L32

**Comment by ernoaapa** [comment]
Thanks for filling the issue.
This is already fixed by https://github.com/ernoaapa/kubectl-warp/pull/3 and will be released soon.
