### ISSUE TITLE
Can we have a v0.0.2 please

### ISSUE THREAD

**Issue by torbjornvatn** [ernoaapa/kubectl-warp#8]
I get the `No Auth Provider found for name "gcp"` and were wondering if you can roll a release with the fixes in #3?

**Comment by ernoaapa** [comment]
Oh yes @torbjornvatn, sorry for that!
I got a child and have been offline but now back :)

**Comment by ernoaapa** [comment]
released https://github.com/ernoaapa/kubectl-warp/releases/tag/v0.0.2
